### ISSUE TITLE
BytePairEncodingCore::encode_native splits special tokens

### ISSUE THREAD

**Issue by mandarddixit** [gh-markt/cpp-tiktoken#5]
Special tokens present in the encoder class (clt100k_base) get treated as natural text in the function encode_native. This despite passing the desired special tokens (using allowed_special) in the function call. At the line auto matches = pattern_string_->get_all_matches(line_to_encode), I see that "<|endoftext|>" for example, gets split into "<|", "endoftext", "|>". The tokens returned are 27 91 8862 728 428 91 29, instead of pre-assigned special token id 100257. Any idea how to fix this?

**Comment by gh-markt** [comment]
The encoding function does not use the special token mappings, those are only used by decode.

To make encode use this would not be easy... basically, it would amount to keeping track of symbols seen so far, and as soon as the token collected so far matches one of the special tokens, all off the tokens pushed so far since we started would have to be popped back off, and replaced with the token from the special mapping.

This is not an impossible change, but I will need some time to consider how to do it elegantly.

**Comment by gh-markt** [comment]
Okay.... this should now be fixed.  Please update to the latest master.

**Comment by mandarddixit** [comment]
pos needs to be reset to 0 before the line "for (auto [begin, end]: separator_offsets) {" in the break_into_specials function. It seems to be working correctly after I do that.

**Comment by gh-markt** [comment]
Ah, thanks.... good eye,   that was a local change but it didn't get pushed for some reason.

**Comment by siemonchan** [comment]
@gh-markt 
Move "pos = 0" to byte_pair_encoding.cc line93, right after each sep being checked, otherwise this function goes wrong when there is more than one special token in 'special_token_mappings_'

**Comment by gh-markt** [comment]
Thank you for your feedback.  I've addressed it in the lastest master branch
